/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

export declare function extractLiterals(code: string, filename: string): JsExtracted

export interface JsExtracted {
  /** Icon-shaped literals, sorted. */
  literals: Array<string>
  /** `false` when the file did not parse and the regex fallback produced `literals`. */
  parsed: boolean
}

export interface JsScanOptions {
  /** Files or directories; relative paths resolve against the process cwd. */
  sources: Array<string>
  /** The icon name set; only these names are reported. */
  names: Array<string>
  /** `globToRegExp(glob).source` strings, matched against root-relative `/` paths. */
  excludeRegex: Array<string>
  /** Cache file (written best-effort). Omit to scan without a cache. */
  cacheFile?: string
  /** Cache key; a fingerprint of `names` is appended internally. */
  cacheKey: string
}

export interface JsScanResult {
  /** All names found, sorted. */
  names: Array<string>
  /** File → names found in it (sorted); only files with hits; keys in sorted path order. */
  byFile: Record<string, Array<string>>
  /** Number of listed source files. */
  files: number
  /** Files that did not parse and were scanned with the regex fallback, sorted. */
  unparsed: Array<string>
  ms: number
}

/**
 * Scans `sources` for icon names (parallel, cached). Throws on a missing source, an invalid
 * exclude pattern, any I/O error other than a file vanishing mid-scan, or a panic.
 */
export declare function scan(options: JsScanOptions): JsScanResult

export declare function version(): string
