import { formatDataJson, renderIconModule, renderNamesModule } from './render';

test('formatDataJson sorts keys and writes one icon per line', () => {
  expect(formatDataJson({ info: { d: 'I', f: 'IF' }, close: { d: 'C' } })).toBe(
    '{\n  "close": {"d":"C"},\n  "info": {"d":"I","f":"IF"}\n}\n',
  );
});

test('renderIconModule emits a one-line CommonJS module and omits f when absent', () => {
  expect(renderIconModule({ d: 'M0 0Z' })).toBe('module.exports={"d":"M0 0Z"};\n');
  expect(renderIconModule({ d: 'A', f: 'B' })).toBe('module.exports={"d":"A","f":"B"};\n');
});

test('renderNamesModule emits literal tuples and alias types', () => {
  const out = renderNamesModule(['info', 'close'], { access_time: 'schedule' }, ['some_legacy']);
  expect(out).toContain('export const MATERIAL_SYMBOL_NAMES = ["close","info"] as const;');
  expect(out).toContain('export type MaterialSymbolName = (typeof MATERIAL_SYMBOL_NAMES)[number];');
  expect(out).toContain('export const MATERIAL_SYMBOL_ALIASES = {"access_time":"schedule"} as const;');
  expect(out).toContain('export const MATERIAL_SYMBOL_LEGACY = ["some_legacy"] as const;');
  expect(out).toContain('export type MaterialSymbolAlias = keyof typeof MATERIAL_SYMBOL_ALIASES | (typeof MATERIAL_SYMBOL_LEGACY)[number];');
  expect(out.startsWith('// @generated by scripts/build-icons.ts')).toBe(true);
});
