import type { IconData } from './aliases';

export function formatDataJson(icons: Record<string, IconData>): string {
  const lines = Object.keys(icons)
    .sort()
    .map((name) => `  ${JSON.stringify(name)}: ${JSON.stringify(icons[name])}`);
  return `{\n${lines.join(',\n')}\n}\n`;
}

export function renderIconModule(icon: IconData): string {
  const data: IconData = icon.f === undefined ? { d: icon.d } : { d: icon.d, f: icon.f };
  return `module.exports=${JSON.stringify(data)};\n`;
}

export function renderNamesModule(names: string[], aliases: Record<string, string>, legacy: string[]): string {
  const sortedAliases = Object.fromEntries(Object.keys(aliases).sort().map((k) => [k, aliases[k]]));
  return [
    '// @generated by scripts/build-icons.ts — do not edit. Source: data/*.json',
    `export const MATERIAL_SYMBOL_NAMES = ${JSON.stringify([...names].sort())} as const;`,
    'export type MaterialSymbolName = (typeof MATERIAL_SYMBOL_NAMES)[number];',
    `export const MATERIAL_SYMBOL_ALIASES = ${JSON.stringify(sortedAliases)} as const;`,
    `export const MATERIAL_SYMBOL_LEGACY = ${JSON.stringify([...legacy].sort())} as const;`,
    'export type MaterialSymbolAlias = keyof typeof MATERIAL_SYMBOL_ALIASES | (typeof MATERIAL_SYMBOL_LEGACY)[number];',
    '',
  ].join('\n');
}
