import fs from 'node:fs';
import path from 'node:path';
import type { MaterialSymbolVariant } from '../types';

export interface RenderRegistryInput {
  variants: MaterialSymbolVariant[];
  names: Iterable<string>;
  aliases: Record<string, string>;
  iconsDir: string;
  exists?: (file: string) => boolean;
  sizeOf?: (file: string) => number;
}

export interface RenderRegistryOutput {
  code: string;
  count: Partial<Record<MaterialSymbolVariant, number>>;
  bytes: number;
  aliasesUsed: number;
}

export function renderRegistry({
  variants,
  names,
  aliases,
  iconsDir,
  exists = fs.existsSync,
  sizeOf = (file) => fs.statSync(file).size,
}: RenderRegistryInput): RenderRegistryOutput {
  const requested = [...new Set(names)].sort();
  const usedAliases: Record<string, string> = {};
  for (const name of requested) if (aliases[name]) usedAliases[name] = aliases[name];
  const targets = [...new Set(requested.map((n) => aliases[n] ?? n))].sort();

  const count: Partial<Record<MaterialSymbolVariant, number>> = {};
  let bytes = 0;
  const lines = ['// @generated by rn-material-symbols — do not edit', 'module.exports = {', "  mode: 'scanned',", '  icons: {'];
  for (const variant of variants) {
    lines.push(`    ${variant}: {`);
    let n = 0;
    for (const name of targets) {
      const file = path.join(iconsDir, variant, `${name}.js`);
      if (!exists(file)) continue;
      lines.push(`      ${JSON.stringify(name)}: require(${JSON.stringify(file)}),`);
      bytes += sizeOf(file);
      n += 1;
    }
    lines.push('    },');
    count[variant] = n;
  }
  lines.push('  },', `  aliases: ${JSON.stringify(usedAliases)},`, '};', '');
  return { code: lines.join('\n'), count, bytes, aliasesUsed: Object.keys(usedAliases).length };
}

export function writeIfChanged(file: string, code: string): boolean {
  if (fs.existsSync(file) && fs.readFileSync(file, 'utf8') === code) return false;
  fs.mkdirSync(path.dirname(file), { recursive: true });
  const tmp = `${file}.${process.pid}.tmp`;
  fs.writeFileSync(tmp, code);
  fs.renameSync(tmp, file);
  return true;
}
