import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { renderRegistry, writeIfChanged } from './renderRegistry';

// every temp dir this file creates is removed after the file's tests
const createdTempDirs: string[] = [];
function tempDir(prefix: string): string {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), prefix));
  createdTempDirs.push(dir);
  return dir;
}
afterAll(() => {
  for (const dir of createdTempDirs) fs.rmSync(dir, { recursive: true, force: true });
});

const iconsDir = '/pkg/icons';
const present = new Set(['/pkg/icons/rounded/info.js', '/pkg/icons/rounded/schedule.js', '/pkg/icons/outlined/info.js']);
const base = { iconsDir, aliases: { access_time: 'schedule' }, exists: (f: string) => present.has(f), sizeOf: () => 100 };

test('uses absolute icon paths, resolves aliases and dedupes targets', () => {
  const out = renderRegistry({ ...base, variants: ['rounded'], names: ['info', 'access_time', 'schedule'] });
  expect(out.code).toBe(
    [
      '// @generated by rn-material-symbols — do not edit',
      'module.exports = {',
      "  mode: 'scanned',",
      '  icons: {',
      '    rounded: {',
      '      "info": require("/pkg/icons/rounded/info.js"),',
      '      "schedule": require("/pkg/icons/rounded/schedule.js"),',
      '    },',
      '  },',
      '  aliases: {"access_time":"schedule"},',
      '};',
      '',
    ].join('\n'),
  );
  expect(out.count).toEqual({ rounded: 2 });
  expect(out.bytes).toBe(200);
  expect(out.aliasesUsed).toBe(1);
});

test('skips names a variant does not have', () => {
  const out = renderRegistry({ ...base, variants: ['rounded', 'outlined'], names: ['schedule'] });
  expect(out.code).toContain('outlined: {\n    },');
  expect(out.count).toEqual({ rounded: 1, outlined: 0 });
});

test('output is deterministic regardless of input order', () => {
  const a = renderRegistry({ ...base, variants: ['rounded'], names: ['schedule', 'info'] }).code;
  const b = renderRegistry({ ...base, variants: ['rounded'], names: ['info', 'schedule'] }).code;
  expect(a).toBe(b);
});

test('writeIfChanged only touches the file when content differs', () => {
  const file = path.join(tempDir('rnms-'), 'deep', 'registry.js');
  expect(writeIfChanged(file, 'a')).toBe(true);
  expect(writeIfChanged(file, 'a')).toBe(false);
  expect(writeIfChanged(file, 'b')).toBe(true);
  expect(fs.readFileSync(file, 'utf8')).toBe('b');
});
